a1=float(input("Enter the sum of x: "))
a2=float(input("Enter the sum of y: "))
c=float(input("Enter the sum of xy: "))
d=float(input("Enter the sum of xx: "))
e=float(input("Enter n: "))
f=float(input("Enter x: "))

a=((a2*d)-(a1*c))/((e*d)-(a1**2))
b=((e*c)-(a2*a1))/((e*d)-d)
y=a+(b*f)
print("Enter the sum of x: ",a1)
print("Enter the sum of y: ",a2)
print("Enter the sum of xy: ",c)
print("Enter the sum of xx: ",d)
print("Enter n: ",e)
print("Enter x: ",f)
print("A= ",a)
print("B= ",b)
print("Y= ",y)
